"""baseline current schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-08-18 21:08:08.160133
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_resources'))
    )
    with op.batch_alter_table('community_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_resources_id'), ['id'], unique=False)

    op.create_table('damage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damage_reports'))
    )
    with op.batch_alter_table('damage_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_reports_id'), ['id'], unique=False)

    op.create_table('disasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('affected_districts', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disasters'))
    )
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disasters_id'), ['id'], unique=False)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(), nullable=False),
    sa.Column('donor_contact', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations'))
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_id'), ['id'], unique=False)

    op.create_table('emergency_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('people_affected', sa.Integer(), nullable=True),
    sa.Column('elderly_members', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('pregnant_women', sa.Integer(), nullable=True),
    sa.Column('members_with_disabilities', sa.Integer(), nullable=True),
    sa.Column('members_with_chronic_illness', sa.Integer(), nullable=True),
    sa.Column('hvi_raw_score', sa.Integer(), nullable=True),
    sa.Column('hvi_score', sa.Integer(), nullable=True),
    sa.Column('hvi_breakdown', sa.Text(), nullable=True),
    sa.Column('ai_priority', sa.String(), nullable=True),
    sa.Column('ai_urgency_score', sa.Integer(), nullable=True),
    sa.Column('final_priority_score', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('priority_override', sa.String(), nullable=True),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('override_updated_at', sa.DateTime(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_requests'))
    )
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_requests_id'), ['id'], unique=False)

    op.create_table('family_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_updates'))
    )
    with op.batch_alter_table('family_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_updates_id'), ['id'], unique=False)

    op.create_table('missing_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('last_seen_location', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missing_persons'))
    )
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missing_persons_id'), ['id'], unique=False)

    op.create_table('personnel_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=True),
    sa.Column('total_needed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personnel_statuses')),
    sa.UniqueConstraint('role_name', name=op.f('uq_personnel_statuses_role_name'))
    )
    with op.batch_alter_table('personnel_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personnel_statuses_id'), ['id'], unique=False)

    op.create_table('relief_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_quantity', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relief_distributions'))
    )
    with op.batch_alter_table('relief_distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relief_distributions_id'), ['id'], unique=False)

    op.create_table('shelters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('capacity_total', sa.Integer(), nullable=True),
    sa.Column('capacity_available', sa.Integer(), nullable=True),
    sa.Column('capacity_beds', sa.Integer(), nullable=True),
    sa.Column('available_beds', sa.Integer(), nullable=True),
    sa.Column('food_stock_days', sa.Integer(), nullable=True),
    sa.Column('contact_details', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('facilities', sa.String(), nullable=True),
    sa.Column('food_stock', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelters'))
    )
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelters_id'), ['id'], unique=False)

    op.create_table('supply_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('critical_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supply_inventories')),
    sa.UniqueConstraint('item_name', name=op.f('uq_supply_inventories_item_name'))
    )
    with op.batch_alter_table('supply_inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_inventories_id'), ['id'], unique=False)

    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteers'))
    )
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_id'))

    op.drop_table('volunteers')
    with op.batch_alter_table('supply_inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_inventories_id'))

    op.drop_table('supply_inventories')
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelters_id'))

    op.drop_table('shelters')
    with op.batch_alter_table('relief_distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relief_distributions_id'))

    op.drop_table('relief_distributions')
    with op.batch_alter_table('personnel_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personnel_statuses_id'))

    op.drop_table('personnel_statuses')
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missing_persons_id'))

    op.drop_table('missing_persons')
    with op.batch_alter_table('family_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_updates_id'))

    op.drop_table('family_updates')
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_requests_id'))

    op.drop_table('emergency_requests')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_id'))

    op.drop_table('donations')
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disasters_id'))

    op.drop_table('disasters')
    with op.batch_alter_table('damage_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_reports_id'))

    op.drop_table('damage_reports')
    with op.batch_alter_table('community_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_resources_id'))

    op.drop_table('community_resources')
    # ### end Alembic commands ###
